<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>DeltaTrack</RootNamespace>
        <PackageId>DeltaTrack</PackageId>
        <Version>1.0.3</Version>
        <Authors>XBlueC</Authors>
        <Description>DeltaTrack - Precise object change detection library. Automatic property tracking and zero-intrusive dirty data monitoring. 精准的对象变更检测库，自动追踪对象属性变化，零侵入式实现脏数据监控。</Description>
        <PackageProjectUrl>https://github.com/XBlueC/DeltaTrack</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/XBlueC/DeltaTrack</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
<!--        <PackageReadmeFile>README.md</PackageReadmeFile>-->
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DeltaTrack.Analyzers" Version="1.0.3" />
<!--        <None Include="../README.md" Pack="true" PackagePath="\"/>-->
    </ItemGroup>
</Project>