<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>DeltaTrack</RootNamespace>
        <PackageId>DeltaTrack</PackageId>
        <Version>1.0.6</Version>
        <Authors>XBlueC</Authors>
        <Description>Precise object change detection library - Generates code at compile time using Roslyn, automatically tracks property changes with zero intrusion, supports nested objects and collection monitoring.</Description>
        <PackageProjectUrl>https://github.com/XBlueC/DeltaTrack</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright 2026 XBlueC</Copyright>
        <PackageTags>change-tracking;dirty-data;roslyn;source-generator;state-tracking</PackageTags>
        <RepositoryUrl>https://github.com/XBlueC/DeltaTrack</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <LangVersion>default</LangVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
        <ProjectReference Include="..\Analyzers\Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <None Include="..\Analyzers\bin\$(Configuration)\netstandard2.0\Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>
</Project>